# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarVo.tv' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'VKVideoPlayer', '~> 0.1'
pod 'Google-Maps-iOS-Utils', '~> 2.1'
pod 'AWSAuthCore', '~> 2.6'
  # Pods for StarVo.tv

  target 'StarVo.tvTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarVo.tvUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
